//////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                  //
// This file was generated by yasmine's ygen @ 2017/04/20 14:03:35.                                 //
//                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef STATE_MACHINE_CREATOR_HPP_
#define STATE_MACHINE_CREATOR_HPP_

#include "yasmine.hpp"
#include "logic.hpp"

namespace examples 
{


#if defined( SX_CPP03_BOOST ) || ( defined(_MSC_VER) && _MSC_VER <=1800 )
Y_EVENT_WITH_ID( E1, 1 )
Y_EVENT_WITH_ID( E2, 2 )
Y_EVENT_WITH_ID( E3, 3 )
Y_EVENT_WITH_ID( E4, 4 )
Y_EVENT_WITH_ID( E5, 5 )
Y_EVENT_WITH_ID( E6, 6 )
Y_EVENT_WITH_ID( E7, 7 )
#else
Y_EVENT_CREATE(E1, 1)
Y_EVENT_CREATE(E2, 2)
Y_EVENT_CREATE(E3, 3)
Y_EVENT_CREATE(E4, 4)
Y_EVENT_CREATE(E5, 5)
Y_EVENT_CREATE(E6, 6)
Y_EVENT_CREATE(E7, 7)
#endif

typedef sxe::SX_UNIQUE_PTR<sxy::sync_state_machine> state_machine_uptr;

state_machine_uptr create_state_machine(const std::string& _name, examples::logic& _logic );

}


#endif
